### ISSUE TITLE
CONTRIBUTING.md?

### ISSUE THREAD

**Issue by whoyawn** [onmyway133/PushNotifications#20]
It would help if there were instructions on how to build this and contribute. I'm able to install this locally on my machine, but I don't know the steps to take to prepare this for release and submit a PR.

**Comment by Ariandr** [comment]
Hi @whoyawn 
I can give you the instructions of how you can build it. After setting up the environment and installing npm packages, instead of running the app locally you can run the command `npm run dist` and it generates installation files for the current OS you are using.

It will generate:
For Mac: `.zip`, `.dmg` (if you build using macOS)
For Windows: `.msi` (if you build using Windows)
For Linux: `.deb`, `.AppImage` (if you build using Linux)

These files are generated in a special folder that you can find if you open the root of the project.

**Comment by Ariandr** [comment]
@whoyawn 
Additionally, there are 2 libraries supporting building the project. I mentioned it in a PR https://github.com/onmyway133/PushNotifications/pull/21

**Important:**
For building with `electron-builder` you need to run `npm run dist`. Generated files end up in the folder `dist`.
For building with `electron-packager` you need to run `npm run release`. Generated files end up in the folder `PushNotifications-darwin-x64`.

To build for Windows & Linux you need to use `electron-builder`. Also, as for me this way is preferable because it creates installable files.

**Comment by onmyway133** [comment]
I think @Ariandr pretty much answered your question @whoyawn , if you have any inquiries, please feel free to open issue.
