### ISSUE TITLE
Where can I find the firebase server key

### ISSUE THREAD

**Issue by kurt-liao** [onmyway133/PushNotifications#68]
Since the firebase messaging api was upgraded to newer version, I can't find the server key on the location that readme file mentioned.

![2022-08-12_16-04](https://user-images.githubusercontent.com/32745146/184313579-bd1f3a42-fa30-4f68-ace5-15293cfe5a10.png)

Can someone help me?

**Comment by Ariandr** [comment]
Hi @kurt-liao 
In order to use our tool, you need to enable Cloud Messaging API (Legacy).
For this you need to click 3 dots icon and enable that service.

After enabling it you will see the needed IDs.

If you don't want to do it, our tool is not for you.

![image](https://user-images.githubusercontent.com/13591333/184416728-06afd036-0030-437b-a2cb-131c8f3167ab.png)

**Comment by kurt-liao** [comment]
> Hi @kurt-liao 
> 
> In order to use our tool, you need to enable Cloud Messaging API (Legacy).
> 
> For this you need to click 3 dots icon and enable that service.
> 
> 
> 
> After enabling it you will see the needed IDs.
> 
> 
> 
> If you don't want to do it, our tool is not for you.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/13591333/184416728-06afd036-0030-437b-a2cb-131c8f3167ab.png)
> 
> 

I got it! Thanks for your help!
